### ISSUE TITLE
Clarification of components of the SDK used

### ISSUE THREAD

**Issue by flakobatako** [OpenInformix/IfxPy#15]
Asking to package the entire CSDK is just unreal.

For example the nodejs library states that it's dependency is only:

 Dependencies
IBM Informix ESQL/C which can be installed using IBM Informix CSDK.

Which is only a part of the entire CSDK. Otherwise if i want to deploy it in a lambda function on AWS i won't be able, because the entire CSDK weigths more than 300 MB IMHO.

**Comment by jsagrera** [comment]
We are working in a "lite" version of CSDK which will include the minimum libraries and files needed to run the Open source Informix drivers, but right now, the only option is to use CSDK.  

There is no need to have everything that gets installed with CSDK. 
Most of 300MB you mentioned are taken by the "jvm" directory (used for the install/uninstall). It is not needed for run-time.
 
The minimum set you'll need (without SSL connections) is be:

 bin
 etc
 gls
 incl
 msg

in total, around 70MB. 
"gls" is the biggest, 55MB, because it contains all the conversion and locale files for all the languages we support. If you know your application which locales your application/database uses, you can delete the rest.
It can be even smaller if you delete stuff from "bin" like "dbaccess" or "oncmsm".

**Comment by flakobatako** [comment]
Ohh ok, understood.

Thanks for taking your time to clarify this. I appreciate that.

I'll close this now.
